### ISSUE TITLE
sligwolf trucks bug on spawning

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/DarkRP-NPC-Car-Dealer#1]

**Comment by BasonTaylor** [comment]
well thats somthing with the addon sligwolfs behalf not this

**Comment by bigbadbeee** [comment]
I am now Developing this for the latest version of stuff I will try to fix this, Iam in school right now so it might be awhile before it is fixed.

**Comment by Bryantdl7** [comment]
Was an issue in sligwolfs
