### ISSUE TITLE
Cars Spawn nocollided

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/DarkRP-NPC-Car-Dealer#2]
Maybe https://github.com/Bryantdl7/NPC-Car-Dealer/blob/master/lua/npcshop/server.lua#L116 is the cause

**Comment by Ligitimenty** [comment]
1 Fix. Nocollide Car Spawn 
-- allowvnocollide - Enable/disable the ability to no-collide a vehicle (for security).
GM.Config.allowvnocollide               = true
