### ISSUE TITLE
Taking over development for latest DarkRP

### ISSUE THREAD

**Issue by bigbadbeee** [Bryantdl7/DarkRP-NPC-Car-Dealer#3]
Hello, Bryantdl
I would like to take over Development of the Car Dealer. You will be one of the authers. 
Signed,
Bigbadbeee(Brad)

**Comment by Bryantdl7** [comment]
Absolutely, just make sure you include the author that I took the code from too. Don't want any copyright infringement.

**Comment by bigbadbeee** [comment]
I will put your name and the auther you took the code from.

**Comment by bigbadbeee** [comment]
Can you transfer they repo to me? So I can mange it easier?

**Comment by Bryantdl7** [comment]
months later, I noticed you never accepted the transfer.
